### ISSUE TITLE
NameError: name 'project' is not defined

### ISSUE THREAD

**Issue by Terminatez** [hnky/AI4DEV01-CustomVision#2]
Traceback (most recent call last):
  File "C:\Users\kevin\Desktop\CSUN-ai\AI4DEV01-CustomVision-master\predict.py", line 9, in <module>
    predictor.classify_image_url(project.id,publish_iteration_name,url=image_url)
NameError: name 'project' is not defined

I have my cv endpoint and prediction key correct, what am I missing?

The training goes through correctly. I had to add import os above the code though.

**Comment by faizkads** [comment]
> Traceback (most recent call last):
> File "C:\Users\kevin\Desktop\CSUN-ai\AI4DEV01-CustomVision-master\predict.py", line 9, in
> predictor.classify_image_url(project.id,publish_iteration_name,url=image_url)
> NameError: name 'project' is not defined
> 
> I have my cv endpoint and prediction key correct, what am I missing?
> 
> The training goes through correctly. I had to add import os above the code though.

how do you solve this? i have the same problem

**Comment by hnky** [comment]
Hi,
Thanks for noticing this!

I have updated the code in "predict.py"
And added "get_project_id.py" to help you find the project id.

Hope this works.
